# Generated by Django 5.2.7 on 2026-05-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('data_usage', models.FloatField(default=0.0, help_text='Data usage in MB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block')], max_length=5)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('range_cidr', models.CharField(help_text='e.g. 192.168.1.0/24', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.FloatField(default=0.0)),
                ('latency', models.FloatField(default=0.0)),
                ('throughput', models.FloatField(default=0.0)),
                ('packet_loss', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='IN_PROGRESS', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='analyzer.device')),
                ('sender_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='analyzer.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='analyzer.network'),
        ),
    ]
