# Generated by Django 5.2.7 on 2026-05-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('latency', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='firewalllog',
            name='latency_impact',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='firewalllog',
            name='throughput_impact',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='firewalllog',
            name='action',
            field=models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block'), ('ATTACK_DETECTED', 'Attack Detected')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttackSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('DDOS', 'DDoS Attack'), ('BRUTE_FORCE', 'Brute Force'), ('SQL_INJECTION', 'SQL Injection'), ('PORT_SCAN', 'Port Scan')], max_length=20)),
                ('intensity', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('target_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.network')),
            ],
        ),
    ]
