# Generated by Django 4.2.7 on 2026-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0003_vpnstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="firewall_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
