# Generated by Django 4.2.7 on 2026-05-06 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0004_network_firewall_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatransfer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
