# Generated by Django 4.2.7 on 2026-05-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0005_datatransfer_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnserver",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
