# Generated by Django 5.2.7 on 2026-05-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_vpnserver_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], default='DENY', max_length=10)),
                ('ip_address', models.CharField(blank=True, help_text='Specific IP or Subnet', max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ALL', 'All Protocols')], default='ALL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
