# Generated by Django 5.2.7 on 2026-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_userdevice_delete_attacksimulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='original_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
