# Generated by Django 5.2.7 on 2026-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_alter_imagetransfer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetransfer',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
