# Generated by Django 5.2.7 on 2026-05-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_alter_imagetransfer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatransfer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='datatransfer',
            name='receiver_device',
        ),
        migrations.RemoveField(
            model_name='datatransfer',
            name='sender_device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='network',
        ),
        migrations.DeleteModel(
            name='VPNServer',
        ),
        migrations.DeleteModel(
            name='DataTransfer',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
