# Generated by Django 5.2.7 on 2026-05-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_remove_datatransfer_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewalllog',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewalllog',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ALL', 'All Protocols')], default='TCP', max_length=10),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ALL', 'All Protocols')], default='TCP', max_length=10),
        ),
    ]
