# Generated by Django 5.2.7 on 2026-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0015_add_tcp_protocol_to_firewalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetransfer',
            name='file_name',
            field=models.CharField(default='file', max_length=255),
        ),
        migrations.AddField(
            model_name='imagetransfer',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagetransfer',
            name='file_type',
            field=models.CharField(default='IMAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='imagetransfer',
            name='ping',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imagetransfer',
            name='transfer_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='firewalllog',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'TCP')], default='TCP', max_length=10),
        ),
        migrations.AlterField(
            model_name='imagetransfer',
            name='image',
            field=models.FileField(upload_to='transfers/'),
        ),
    ]
